function files = Get_ChAT_Files()
% list of file names Headers and directories 
%cd 'D:\Inbal M.Sc\Data PhD\ChAT Data\Extracted Data'
% called by Extract_ChAT_Data
   
%1.   Set2-2012-11-20-001.exp2       ChAT mouse, LFP recording
% try
%     load('ChAT_Files')
% catch E
%     disp('No file');
%     files=[];
% end
files(1).name = 'Set2-2012-11-20-001.exp2';
files(1).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(1).exp = 'Barrel cortex LFP';
files(1).type = 'ChAT';         %mouse #15. perfused
files(1).electrode_resist = [];
files(1).depth = [];
files(1).pr_whisker = [];
files(1).adj_whisker = [];                                            
files(1).headers = 1:27;
files(1).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano
files(1).header_stim(2).type = 8;
files(1).header_stim(3).type = 8;
files(1).header_stim(4).type = 7;
files(1).header_stim(5).type = 7;
files(1).header_stim(6).type = 8;
files(1).header_stim(7).type = 3;
files(1).header_stim(8).type = 4;
files(1).header_stim(9).type = 3;
files(1).header_stim(10).type = 4;
files(1).header_stim(11).type = 4;
files(1).header_stim(12).type = 3;
files(1).header_stim(13).type = 4;
files(1).header_stim(14).type = 3;
files(1).header_stim(15).type = 7;
files(1).header_stim(16).type = 7;
files(1).header_stim(17).type = 7;
files(1).header_stim(18).type = 7;
files(1).header_stim(19).type = 3;
files(1).header_stim(20).type = 4;
files(1).header_stim(21).type = 3;
files(1).header_stim(22).type = 4;
files(1).header_stim(23).type = 3;
files(1).header_stim(24).type = 4;
files(1).header_stim(25).type = 3;
files(1).header_stim(26).type = 4;
files(1).header_stim(27).type = 3;
files(1).channel_Vm = 1;                        
files(1).channel_LFP = 7;                       %channel extra1 through MCP
files(1).channel_galvano = 11;
files(1).channel_airpuff = 13;
files(1).channel_EKG = 6;
files(1).channel_EEG = 5;
files(1).channel_laser = 10;                %optogenetic stimulation
files(1).galvano = 1;
files(1).comments = [];
files(1).offset = [];                                                   %need to subtract the offset

files(2).name = 'Set2-2012-12-26-001.exp2';
files(2).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(2).exp = 'Barrel cortex LFP';
files(2).type = 'ChAT';         %mouse #8.
files(2).electrode_resist = [];
files(2).depth = [];
files(2).pr_whisker = [];
files(2).adj_whisker = [];                                            
files(2).headers = 1:2;
files(2).header_stim(1).type = 7;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(2).header_stim(2).type = 7;
files(2).channel_Vm = 1;                        
files(2).channel_LFP = 7;                       %channel extra1 through MCP
files(2).channel_galvano = 11;
files(2).channel_airpuff = 13;
files(2).channel_EKG = 6;
files(2).channel_EEG = 5;
files(2).channel_laser = 10;                %optogenetic stimulation
files(2).galvano = 2;
files(2).comments = [];
files(2).offset = [];                                                   %need to subtract the offset

files(3).name = 'Set2-2013-01-03-001.exp2';
files(3).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(3).exp = 'Barrel cortex LFP';
files(3).type = 'ChAT';         %mouse #.
files(3).electrode_resist = [];
files(3).depth = [433 433 754];
files(3).pr_whisker = [];
files(3).adj_whisker = [];                                            
files(3).headers = 1:3;
files(3).header_stim(1).type = 7;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(3).header_stim(2).type = 7;
files(3).header_stim(3).type = 7;
files(3).channel_Vm = 1;                        
files(3).channel_LFP = 7;                       %channel extra1 through MCP
files(3).channel_galvano = 11;
files(3).channel_airpuff = 13;
files(3).channel_EKG = 6;
files(3).channel_EEG = 5;
files(3).channel_laser = 10;                %optogenetic stimulation
files(3).galvano = 2;
files(3).comments = [];
files(3).offset = [];                                                   %need to subtract the offset

files(4).name = 'Set2-2013-01-09-001.exp2';
files(4).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(4).exp = 'Barrel cortex cell attached';
files(4).type = 'ChAT';         %mouse #17.
files(4).electrode_resist = [];
files(4).depth = [];
files(4).pr_whisker = [];
files(4).adj_whisker = [];                                            
files(4).headers = 1:2;
files(4).header_stim(1).type = 7;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(4).header_stim(2).type = 7;
files(4).channel_Vm = 1;                        
files(4).channel_LFP = 7;                       %channel extra1 through MCP
files(4).channel_galvano = 11;
files(4).channel_airpuff = 13;
files(4).channel_EKG = 6;
files(4).channel_EEG = 5;
files(4).channel_laser = 10;                %optogenetic stimulation
files(4).galvano = 2;
files(4).comments = [];
files(4).offset = [];                                                   %need to subtract the offset

files(5).name = 'Set2-2013-01-13-001.exp2';
files(5).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(5).exp = 'Barrel cortex intracellular';
files(5).type = 'WT';       
files(5).electrode_resist = 8;
files(5).depth = 349;
files(5).pr_whisker = 'Gamma(stradler btween C and D)';
files(5).adj_whisker = [];                                            
files(5).headers = [1,3:6];
files(5).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(5).header_stim(2).type = 5;
files(5).header_stim(3).type = 5;
files(5).header_stim(4).type = 8;
files(5).header_stim(5).type = 8;
files(5).channel_Vm = 1;                        
files(5).channel_LFP = 7;                       %channel extra1 through MCP
files(5).channel_galvano = 11;
files(5).channel_airpuff = 13;
files(5).channel_EKG = 6;
files(5).channel_EEG = 5;
files(5).channel_laser = 10;                %optogenetic stimulation
files(5).galvano = 2;
files(5).comments = 'header 6 is a different cell, depth 524. galvano didnt work (wrong channel), bio+QX, isofluran';
files(5).offset = [];

files(6).name = 'Set2-2013-02-13-001.exp2';
files(6).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(6).exp = 'Barrel cortex LFP';
files(6).type = 'ChAT';         %mouse #20.
files(6).electrode_resist = 8; %[MOhm]
files(6).depth = 391; %[um]
files(6).pr_whisker = 'B1';
files(6).adj_whisker = [];                                            
files(6).headers = 1:3;
files(6).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(6).header_stim(2).type = 8;
files(6).header_stim(3).type = 8;
files(6).channel_Vm = 1;                        
files(6).channel_LFP = 7;                       %channel extra1 through MCP
files(6).channel_galvano = 11;
files(6).channel_airpuff = 13;
files(6).channel_EKG = 6;
files(6).channel_EEG = 5;
files(6).channel_laser = 10;                %optogenetic stimulation
files(6).galvano = 2;
files(6).comments = 'each header different depth, fiber above brain';
files(6).offset = [];                                                   %need to subtract the offset

files(7).name = 'Set2-2013-02-13-002.exp2';
files(7).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(7).exp = 'Barrel cortex LFP';
files(7).type = 'ChAT';         %mouse #20.
files(7).electrode_resist = 8; %[MOhm]
files(7).depth = 100; %[um]
files(7).pr_whisker = 'B1';
files(7).adj_whisker = [];                                            
files(7).headers = 2:4;
files(7).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(7).header_stim(2).type = 8;
files(7).header_stim(3).type = 8;
files(7).channel_Vm = 1;                        
files(7).channel_LFP = 7;                       %channel extra1 through MCP
files(7).channel_galvano = 11;
files(7).channel_airpuff = 13;
files(7).channel_EKG = 6;
files(7).channel_EEG = 5;
files(7).channel_laser = 10;                %optogenetic stimulation
files(7).galvano = 2;
files(7).comments = 'each header different depth';
files(7).offset = [];                                                   %need to subtract the offset

files(8).name = 'Set2-2013-02-13-003.exp2';
files(8).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(8).exp = 'Barrel cortex intracellular';
files(8).type = 'ChAT';         %mouse #20.
files(8).electrode_resist = 8; %[MOhm]
files(8).depth = []; %[um]
files(8).pr_whisker = 'B1';
files(8).adj_whisker = [];                                            
files(8).headers = 1;
files(8).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(8).channel_Vm = 1;                        
files(8).channel_LFP = 7;                       %channel extra1 through MCP
files(8).channel_galvano = 11;
files(8).channel_airpuff = 13;
files(8).channel_EKG = 6;
files(8).channel_EEG = 5;
files(8).channel_laser = 10;                %optogenetic stimulation
files(8).galvano = 2;
files(8).comments = [];
files(8).offset = [];                                                   %need to subtract the offset

files(9).name = 'Set2-2013-02-13-004.exp2';
files(9).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(9).exp = 'Barrel cortex intracellular';
files(9).type = 'ChAT';         %mouse #20.
files(9).electrode_resist = 7; %[MOhm]
files(9).depth = 453; %[um]
files(9).pr_whisker = 'B1';
files(9).adj_whisker = [];                                            
files(9).headers = 1;
files(9).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(9).channel_Vm = 1;                        
files(9).channel_LFP = 7;                       %channel extra1 through MCP
files(9).channel_galvano = 11;
files(9).channel_airpuff = 13;
files(9).channel_EKG = 6;
files(9).channel_EEG = 5;
files(9).channel_laser = 10;                %optogenetic stimulation
files(9).galvano = 2;
files(9).comments = [];
files(9).offset = [];                                                   %need to subtract the offset

files(10).name = 'Set2-2013-02-13-005.exp2';
files(10).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(10).exp = 'Barrel cortex intracellular';
files(10).type = 'ChAT';         %mouse #20.
files(10).electrode_resist = 8; %[MOhm]
files(10).depth = []; %[um]
files(10).pr_whisker = 'B1';
files(10).adj_whisker = [];                                            
files(10).headers = 1:4;
files(10).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(10).header_stim(2).type = 3;
files(10).header_stim(3).type = 8;
files(10).header_stim(4).type = 8;
files(10).channel_Vm = 1;                        
files(10).channel_LFP = 7;                       %channel extra1 through MCP
files(10).channel_galvano = 11;
files(10).channel_airpuff = 13;
files(10).channel_EKG = 6;
files(10).channel_EEG = 5;
files(10).channel_laser = 10;                %optogenetic stimulation
files(10).galvano = 2;
files(10).comments = [];
files(10).offset = [];                                                   %need to subtract the offset

files(11).name = 'Set2-2013-02-18-002.exp2';
files(11).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(11).exp = 'Basal Forebrain LFP';
files(11).type = 'ChAT';         %mouse #22. 
files(11).electrode_resist = []; %[MOhm]
files(11).depth = 3934; %[um]
files(11).pr_whisker = [];
files(11).adj_whisker = [];                                            
files(11).headers = 2:5;
files(11).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(11).header_stim(2).type = 2;
files(11).header_stim(3).type = 1;
files(11).header_stim(4).type = 2;
files(11).channel_Vm = 1;                        
files(11).channel_LFP = 7;                       %channel extra1 through MCP
files(11).channel_galvano = 11;
files(11).channel_airpuff = 13;
files(11).channel_EKG = 6;
files(11).channel_EEG = 5;
files(11).channel_laser = 10;                %optogenetic stimulation
files(11).galvano = [];
files(11).comments = [];
files(11).offset = [];                                                   %need to subtract the offset

files(12).name = 'Set2-2013-02-18-003.exp2';
files(12).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(12).exp = 'Basal Forebrain LFP';
files(12).type = 'ChAT';         %mouse #22. 
files(12).electrode_resist = []; %[MOhm]
files(12).depth = 3030; %[um]
files(12).pr_whisker = [];
files(12).adj_whisker = [];                                            
files(12).headers = 1:3;
files(12).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(12).header_stim(2).type = 1;
files(12).header_stim(3).type = 2;
files(12).channel_Vm = 1;                        
files(12).channel_LFP = 7;                       %channel extra1 through MCP
files(12).channel_galvano = 11;
files(12).channel_airpuff = 13;
files(12).channel_EKG = 6;
files(12).channel_EEG = 5;
files(12).channel_laser = 10;                %optogenetic stimulation
files(12).galvano = [];
files(12).comments = 'with DiI';
files(12).offset = [];                                                   %need to subtract the offset

files(13).name = 'Set2-2013-02-18-004.exp2';
files(13).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(13).exp = 'Basal Forebrain LFP';
files(13).type = 'ChAT';         %mouse #22. 
files(13).electrode_resist = []; %[MOhm]
files(13).depth = 4837; %[um]
files(13).pr_whisker = [];
files(13).adj_whisker = [];                                            
files(13).headers = [1,3];
files(13).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(13).header_stim(2).type = 2;
files(13).channel_Vm = 1;                        
files(13).channel_LFP = 7;                       %channel extra1 through MCP
files(13).channel_galvano = 11;
files(13).channel_airpuff = 13;
files(13).channel_EKG = 6;
files(13).channel_EEG = 5;
files(13).channel_laser = 10;                %optogenetic stimulation
files(13).galvano = [];
files(13).comments = 'with DiI';
files(13).offset = [];                                                   %need to subtract the offset

files(14).name = 'Set2-2013-02-18-005.exp2';
files(14).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(14).exp = 'Basal Forebrain LFP';
files(14).type = 'ChAT';         %mouse #22. 
files(14).electrode_resist = []; %[MOhm]
files(14).depth = 4237; %[um]
files(14).pr_whisker = [];
files(14).adj_whisker = [];                                            
files(14).headers = 1:3;
files(14).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(14).header_stim(2).type = 2;
files(14).header_stim(3).type = 1;
files(14).channel_Vm = 1;                        
files(14).channel_LFP = 7;                       %channel extra1 through MCP
files(14).channel_galvano = 11;
files(14).channel_airpuff = 13;
files(14).channel_EKG = 6;
files(14).channel_EEG = 5;
files(14).channel_laser = 10;                %optogenetic stimulation
files(14).galvano = [];
files(14).comments = 'with DiI';
files(14).offset = [];                                                   %need to subtract the offset

files(15).name = 'Set2-2013-02-18-006.exp2';
files(15).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(15).exp = 'Basal Forebrain LFP';
files(15).type = 'ChAT';         %mouse #22. 
files(15).electrode_resist = []; %[MOhm]
files(15).depth = 4777; %[um]
files(15).pr_whisker = [];
files(15).adj_whisker = [];                                            
files(15).headers = 1:2;
files(15).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(15).header_stim(2).type = 2;
files(15).channel_Vm = 1;                        
files(15).channel_LFP = 7;                       %channel extra1 through MCP
files(15).channel_galvano = 11;
files(15).channel_airpuff = 13;
files(15).channel_EKG = 6;
files(15).channel_EEG = 5;
files(15).channel_laser = 10;                %optogenetic stimulation
files(15).galvano = [];
files(15).comments = 'with DiI';
files(15).offset = [];                                                   %need to subtract the offset

files(16).name = 'Set2-2013-02-18-007.exp2';
files(16).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(16).exp = 'Basal Forebrain LFP';
files(16).type = 'ChAT';         %mouse #22. 
files(16).electrode_resist = []; %[MOhm]
files(16).depth = 4668; %[um]
files(16).pr_whisker = [];
files(16).adj_whisker = [];                                            
files(16).headers = 1:5;
files(16).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(16).header_stim(2).type = 2;
files(16).header_stim(3).type = 2;
files(16).header_stim(4).type = 1;
files(16).header_stim(5).type = 2;
files(16).channel_Vm = 1;                        
files(16).channel_LFP = 7;                       %channel extra1 through MCP
files(16).channel_galvano = 11;
files(16).channel_airpuff = 13;
files(16).channel_EKG = 6;
files(16).channel_EEG = 5;
files(16).channel_laser = 10;                %optogenetic stimulation
files(16).galvano = [];
files(16).comments = 'with DiI';
files(16).offset = [];                                                   %need to subtract the offset

files(17).name = 'Set2-2013-02-18-008.exp2';
files(17).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(17).exp = 'Basal Forebrain LFP';
files(17).type = 'ChAT';         %mouse #22. 
files(17).electrode_resist = []; %[MOhm]
files(17).depth = 4085; %[um]
files(17).pr_whisker = [];
files(17).adj_whisker = [];                                            
files(17).headers = 1:4;
files(17).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(17).header_stim(2).type = 2;
files(17).header_stim(3).type = 2;
files(17).header_stim(4).type = 2;
files(17).channel_Vm = 1;                        
files(17).channel_LFP = 7;                       %channel extra1 through MCP
files(17).channel_galvano = 11;
files(17).channel_airpuff = 13;
files(17).channel_EKG = 6;
files(17).channel_EEG = 5;
files(17).channel_laser = 10;                %optogenetic stimulation
files(17).galvano = [];
files(17).comments = [];
files(17).offset = [];                                                   %need to subtract the offset

files(18).name = 'Set2-2013-02-27-001.exp2';
files(18).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(18).exp = 'Basal Forebrain LFP';
files(18).type = 'ChAT';         %mouse #27. 
files(18).electrode_resist = []; %[MOhm]
files(18).depth = 4200; %[um]
files(18).pr_whisker = [];
files(18).adj_whisker = [];                                            
files(18).headers = 2;
files(18).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(18).channel_Vm = 1;                        
files(18).channel_LFP = 7;                       %channel extra1 through MCP
files(18).channel_galvano = 11;
files(18).channel_airpuff = 13;
files(18).channel_EKG = 6;
files(18).channel_EEG = 5;
files(18).channel_laser = 10;                %optogenetic stimulation
files(18).galvano = [];
files(18).comments = [];
files(18).offset = [];                                                   %need to subtract the offset

files(19).name = 'Set2-2013-02-27-002.exp2';
files(19).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(19).exp = 'Basal Forebrain LFP';
files(19).type = 'ChAT';         %mouse #27. 
files(19).electrode_resist = []; %[MOhm]
files(19).depth = 4120; %[um]
files(19).pr_whisker = [];
files(19).adj_whisker = [];                                            
files(19).headers = 1:7;
files(19).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(19).header_stim(2).type = 2;
files(19).header_stim(3).type = 2;
files(19).header_stim(4).type = 1;
files(19).header_stim(5).type = 2;
files(19).header_stim(6).type = 2;
files(19).header_stim(7).type = 2;
files(19).channel_Vm = 1;                        
files(19).channel_LFP = 7;                       %channel extra1 through MCP
files(19).channel_galvano = 11;
files(19).channel_airpuff = 13;
files(19).channel_EKG = 6;
files(19).channel_EEG = 5;
files(19).channel_laser = 10;                %optogenetic stimulation
files(19).galvano = [];
files(19).comments = 'penetration with DiI to the same point after the recording';
files(19).offset = 30;                                                   %need to subtract the offset

files(20).name = 'Set2-2013-02-27-003.exp2';
files(20).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(20).exp = 'Basal Forebrain extracellular';
files(20).type = 'ChAT';         %mouse #27. 
files(20).electrode_resist = []; %[MOhm]
files(20).depth = 4780; %[um]
files(20).pr_whisker = [];
files(20).adj_whisker = [];                                            
files(20).headers = 1:11;
files(20).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(20).header_stim(2).type = 2;
files(20).header_stim(3).type = 2;
files(20).header_stim(4).type = 2;
files(20).header_stim(5).type = 2;
files(20).header_stim(6).type = 2;
files(20).header_stim(7).type = 2;
files(20).header_stim(8).type = 2;
files(20).header_stim(9).type = 2;
files(20).header_stim(10).type = 1;
files(20).header_stim(11).type = 2;
files(20).channel_Vm = 1;                        
files(20).channel_LFP = 7;                       %channel extra1 through MCP
files(20).channel_galvano = 11;
files(20).channel_airpuff = 13;
files(20).channel_EKG = 6;
files(20).channel_EEG = 5;
files(20).channel_laser = 10;                %optogenetic stimulation
files(20).galvano = [];
files(20).comments = 'penetration with DiI to the same point after the recording';
files(20).offset = 30;                                                   %need to subtract the offset

files(21).name = 'Set2-2013-03-20-001.exp2';
files(21).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(21).exp = 'Motor cortex LFP';
files(21).type = 'ChAT';         %mouse #23. 
files(21).electrode_resist = []; %[MOhm]
files(21).depth = []; %[um]
files(21).pr_whisker = [];
files(21).adj_whisker = [];                                            
files(21).headers = 2:7;
files(21).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(21).header_stim(2).type = 8;
files(21).header_stim(3).type = 8;
files(21).header_stim(4).type = 8;
files(21).header_stim(5).type = 8;
files(21).header_stim(6).type = 8;
files(21).channel_Vm = 1;                        
files(21).channel_LFP = 7;                       %channel extra1 through MCP
files(21).channel_galvano = 11;
files(21).channel_airpuff = 13;
files(21).channel_EKG = 6;
files(21).channel_EEG = 5;
files(21).channel_laser = 10;                %optogenetic stimulation
files(21).galvano = [];
files(21).comments = 'LFP recording of LFP with optopatcher in M1';
files(21).offset = [];

files(22).name = 'Set2-2013-03-20-002.exp2';
files(22).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(22).exp = 'Basal Forebrain extracellular';
files(22).type = 'ChAT';         %mouse #23. 
files(22).electrode_resist = []; %[MOhm]
files(22).depth = 4104; %[um]
files(22).pr_whisker = [];
files(22).adj_whisker = [];                                            
files(22).headers = 1:12;
files(22).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(22).header_stim(2).type = 2;
files(22).header_stim(3).type = 2;
files(22).header_stim(4).type = 2;
files(22).header_stim(5).type = 2;
files(22).header_stim(6).type = 2;
files(22).header_stim(7).type = 2;
files(22).header_stim(8).type = 2;
files(22).header_stim(9).type = 2;
files(22).header_stim(10).type = 2;
files(22).header_stim(11).type = 2;
files(22).header_stim(12).type = 2;
files(22).channel_Vm = 1;                        
files(22).channel_LFP = 7;                       %channel extra1 through MCP
files(22).channel_galvano = 11;
files(22).channel_airpuff = 13;
files(22).channel_EKG = 6;
files(22).channel_EEG = 5;
files(22).channel_laser = 10;                %optogenetic stimulation
files(22).galvano = [];
files(22).comments = 'M.U. recording in BF with optopatcher';
files(22).offset = [];

files(23).name = 'Set2-2013-04-03-001.exp2';
files(23).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(23).exp = 'Basal Forebrain extracellular';
files(23).type = 'ChAT';         %mouse #31. 
files(23).electrode_resist = []; %[MOhm]
files(23).depth = 3680; %[um]
files(23).pr_whisker = [];
files(23).adj_whisker = [];                                            
files(23).headers = 2;
files(23).header_stim(1).type = 1;                        
files(23).channel_Vm = 1;                        
files(23).channel_LFP = 7;                       %channel extra1 through MCP
files(23).channel_galvano = 11;
files(23).channel_airpuff = 13;
files(23).channel_EKG = 6;
files(23).channel_EEG = 5;
files(23).channel_laser = 10;                %optogenetic stimulation
files(23).galvano = [];
files(23).comments = 'M.U. recording in BF with optopatcher';   %this cell spiked in correlation with the EEG 
files(23).offset = [];

files(24).name = 'Set2-2013-04-03-002.exp2';
files(24).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(24).exp = 'Basal Forebrain extracellular';
files(24).type = 'ChAT';         %mouse #31. 
files(24).electrode_resist = []; %[MOhm]
files(24).depth = 4100; %[um]
files(24).pr_whisker = [];
files(24).adj_whisker = [];                                            
files(24).headers = 1:9;
files(24).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(24).header_stim(2).type = 2;
files(24).header_stim(3).type = 2;
files(24).header_stim(4).type = 2;
files(24).header_stim(5).type = 2;
files(24).header_stim(6).type = 1;
files(24).header_stim(7).type = 2;
files(24).header_stim(8).type = 2;
files(24).header_stim(9).type = 2;
files(24).channel_Vm = 1;                        
files(24).channel_LFP = 7;                       %channel extra1 through MCP
files(24).channel_galvano = 11;
files(24).channel_airpuff = 13;
files(24).channel_EKG = 6;
files(24).channel_EEG = 5;
files(24).channel_laser = 10;                %optogenetic stimulation
files(24).galvano = [];
files(24).comments = 'M.U. recording in BF with optopatcher';
files(24).offset = [];

files(25).name = 'Set2-2013-06-12-001.exp2';
files(25).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(25).exp = 'Barrel cortex LFP, awake';
files(25).type = 'ChAT';         %mouse #35. 
files(25).electrode_resist = 10; %[MOhm]
files(25).depth = 51; %[um]
files(25).pr_whisker = [];
files(25).adj_whisker = [];                                            
files(25).headers = 1;
files(25).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(25).channel_Vm = 1;                        
files(25).channel_LFP = 7;                       %channel extra1 through MCP
files(25).channel_galvano = 11;
files(25).channel_airpuff = 13;
files(25).channel_EKG = 6;
files(25).channel_EEG = 5;
files(25).channel_laser = 10;                %optogenetic stimulation
files(25).galvano = [];
files(25).comments = 'LFP recording in BC with patch electrode and fiber optic above the cortex, "protocol ChAT LFP: laser only"';
files(25).offset = [];

files(26).name = 'Set2-2013-06-12-002.exp2';
files(26).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(26).exp = 'Barrel cortex LFP, awake';
files(26).type = 'ChAT';         %mouse #35. 
files(26).electrode_resist = 10; %[MOhm]
files(26).depth = 200; %[um]
files(26).pr_whisker = [];
files(26).adj_whisker = [];                                            
files(26).headers = 1;
files(26).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(26).channel_Vm = 1;                        
files(26).channel_LFP = 7;                       %channel extra1 through MCP
files(26).channel_galvano = 11;
files(26).channel_airpuff = 13;
files(26).channel_EKG = 6;
files(26).channel_EEG = 5;
files(26).channel_laser = 10;                %optogenetic stimulation
files(26).galvano = [];
files(26).comments = 'same as file Set2-2013-06-12-001.exp2';
files(26).offset = [];

files(27).name = 'Set2-2013-06-12-003.exp2';
files(27).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(27).exp = 'Barrel cortex LFP, awake';
files(27).type = 'ChAT';         %mouse #35. 
files(27).electrode_resist = 10; %[MOhm]
files(27).depth = 400; %[um]
files(27).pr_whisker = [];
files(27).adj_whisker = [];                                            
files(27).headers = 1;
files(27).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(27).channel_Vm = 1;                        
files(27).channel_LFP = 7;                       %channel extra1 through MCP
files(27).channel_galvano = 11;
files(27).channel_airpuff = 13;
files(27).channel_EKG = 6;
files(27).channel_EEG = 5;
files(27).channel_laser = 10;                %optogenetic stimulation
files(27).galvano = [];
files(27).comments = 'same as file Set2-2013-06-12-001.exp2';
files(27).offset = [];

files(28).name = 'Set2-2013-06-12-004.exp2';
files(28).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(28).exp = 'Barrel cortex LFP, awake';
files(28).type = 'ChAT';         %mouse #35. 
files(28).electrode_resist = 10; %[MOhm]
files(28).depth = 600; %[um]
files(28).pr_whisker = [];
files(28).adj_whisker = [];                                            
files(28).headers = 1;
files(28).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(28).channel_Vm = 1;                        
files(28).channel_LFP = 7;                       %channel extra1 through MCP
files(28).channel_galvano = 11;
files(28).channel_airpuff = 13;
files(28).channel_EKG = 6;
files(28).channel_EEG = 5;
files(28).channel_laser = 10;                %optogenetic stimulation
files(28).galvano = [];
files(28).comments = 'same as file Set2-2013-06-12-001.exp2';
files(28).offset = [];

files(29).name = 'Set2-2013-06-12-005.exp2';
files(29).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(29).exp = 'Barrel cortex LFP, awake';
files(29).type = 'ChAT';         %mouse #35. 
files(29).electrode_resist = 10; %[MOhm]
files(29).depth = 810; %[um]
files(29).pr_whisker = [];
files(29).adj_whisker = [];                                            
files(29).headers = 1;
files(29).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(29).channel_Vm = 1;                        
files(29).channel_LFP = 7;                       %channel extra1 through MCP
files(29).channel_galvano = 11;
files(29).channel_airpuff = 13;
files(29).channel_EKG = 6;
files(29).channel_EEG = 5;
files(29).channel_laser = 10;                %optogenetic stimulation
files(29).galvano = [];
files(29).comments = 'same as file Set2-2013-06-12-001.exp2';
files(29).offset = [];

files(30).name = 'Set2-2013-07-16-001.exp2';
files(30).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(30).exp = 'PFC extracellular';
files(30).type = 'ChAT';         %mouse #8. 
files(30).electrode_resist = []; %[MOhm]
files(30).depth = 2000; %[um]
files(30).pr_whisker = [];
files(30).adj_whisker = [];                                            
files(30).headers = 1:3;
files(30).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(30).header_stim(2).type = 2;  
files(30).header_stim(3).type = 2;  
files(30).channel_Vm = 1;                        
files(30).channel_LFP = 7;                       %channel extra1 through MCP
files(30).channel_galvano = 11;
files(30).channel_airpuff = 13;
files(30).channel_EKG = 6;
files(30).channel_EEG = 5;
files(30).channel_laser = 10;                %optogenetic stimulation
files(30).galvano = [];
files(30).comments = '';
files(30).offset = [];

files(31).name = 'Set2-2013-07-16-002.exp2';
files(31).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(31).exp = 'PFC LFP';
files(31).type = 'ChAT';         %mouse #8. 
files(31).electrode_resist = 15; %[MOhm]
files(31).depth = 2160; %[um]
files(31).pr_whisker = [];
files(31).adj_whisker = [];                                            
files(31).headers = [1,2,4];
files(31).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(31).header_stim(2).type = 2;  
files(31).header_stim(3).type = 2;  
files(31).channel_Vm = 1;                        
files(31).channel_LFP = 7;                       %channel extra1 through MCP
files(31).channel_galvano = 11;
files(31).channel_airpuff = 13;
files(31).channel_EKG = 6;
files(31).channel_EEG = 5;
files(31).channel_laser = 10;                %optogenetic stimulation
files(31).galvano = [];
files(31).comments = '';
files(31).offset = [];

files(32).name = 'Set2-2013-07-16-003.exp2';
files(32).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(32).exp = 'PFC cell attached';
files(32).type = 'ChAT';         %mouse #8. 
files(32).electrode_resist = 5; %[MOhm]
files(32).depth = 2272; %[um]
files(32).pr_whisker = [];
files(32).adj_whisker = [];                                            
files(32).headers = [1,3:6];
files(32).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(32).header_stim(2).type = 2;  
files(32).header_stim(3).type = 1;  
files(32).header_stim(4).type = 2;  
files(32).header_stim(5).type = 1;  
files(32).channel_Vm = 1;                        
files(32).channel_LFP = 7;                       %channel extra1 through MCP
files(32).channel_galvano = 11;
files(32).channel_airpuff = 13;
files(32).channel_EKG = 6;
files(32).channel_EEG = 5;
files(32).channel_laser = 10;                %optogenetic stimulation
files(32).galvano = [];
files(32).comments = '';
files(32).offset = [];

files(33).name = 'Set2-2013-07-16-004.exp2';
files(33).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(33).exp = 'PFC cell attached';
files(33).type = 'ChAT';         %mouse #8. 
files(33).electrode_resist = 5; %[MOhm]
files(33).depth = 2350; %[um]
files(33).pr_whisker = [];
files(33).adj_whisker = [];                                            
files(33).headers = [1:6];
files(33).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(33).header_stim(2).type = 2;  
files(33).header_stim(3).type = 2;  
files(33).header_stim(4).type = 2;  
files(33).header_stim(5).type = 1;  
files(33).header_stim(6).type = 8;  
files(33).channel_Vm = 1;                        
files(33).channel_LFP = 7;                       %channel extra1 through MCP
files(33).channel_galvano = 11;
files(33).channel_airpuff = 13;
files(33).channel_EKG = 6;
files(33).channel_EEG = 5;
files(33).channel_laser = 10;                %optogenetic stimulation
files(33).galvano = [];
files(33).comments = 'with QX';
files(33).offset = '';

files(34).name = '2013-10-28-001.exp2'; %set 1
files(34).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(34).exp = 'Barrel cortex LFP'; %optic fiber above cortex.
files(34).type = 'ChAT';         %mouse #1. 
files(34).electrode_resist = []; %[MOhm]
files(34).depth = []; %[um]
files(34).pr_whisker = [];
files(34).adj_whisker = [];                                            
files(34).headers = 1:2;
files(34).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(34).header_stim(2).type = 2;  
files(34).channel_Vm = 1;                        
files(34).channel_LFP = 2;                       
files(34).channel_galvano = 15;
files(34).channel_airpuff = 13;
files(34).channel_EKG = 6;
files(34).channel_EEG = 2;
files(34).channel_laser = 10;                %optogenetic stimulation
files(34).galvano = [];
files(34).comments = '';
files(34).offset = [];

files(35).name = '2013-10-28-002.exp2'; %set 1
files(35).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(35).exp = 'Barrel cortex LFP'; %optopatcher in BF.
files(35).type = 'ChAT';         %mouse #1. 
files(35).electrode_resist = []; %[MOhm]
files(35).depth = []; %[um]
files(35).pr_whisker = [];
files(35).adj_whisker = [];                                            
files(35).headers = 1:4;
files(35).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(35).header_stim(2).type = 2;  
files(35).header_stim(3).type = 2;
files(35).header_stim(4).type = 2;
files(35).channel_Vm = 1;                        
files(35).channel_LFP = 2;                       
files(35).channel_galvano = 15;
files(35).channel_airpuff = 13;
files(35).channel_EKG = 6;
files(35).channel_EEG = 2;
files(35).channel_laser = 10;                %optogenetic stimulation
files(35).galvano = [];
files(35).comments ='';
files(35).offset = [];

files(36).name = '2013-10-28-003.exp2'; %set 1
files(36).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(36).exp = 'Barrel cortex intracellular'; %optopatcher in BF.
files(36).type = 'ChAT';         %mouse #1. Cell #1
files(36).electrode_resist = []; %[MOhm]
files(36).depth = []; %[um]
files(36).pr_whisker = [];
files(36).adj_whisker = [];                                            
files(36).headers = 2:4;
files(36).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(36).header_stim(2).type = 3;  
files(36).header_stim(3).type = 4;
files(36).channel_Vm = 1;                        
files(36).channel_LFP = 2;                       
files(36).channel_galvano = 15;
files(36).channel_airpuff = 13;
files(36).channel_EKG = 6;
files(36).channel_EEG = 2;
files(36).channel_laser = 10;                %optogenetic stimulation
files(36).galvano = [];
files(36).comments ='';
files(36).offset = 18;

files(37).name = 'Set2-2014-03-12-001.exp2';
files(37).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(37).exp = 'Barrel cortex LFP'; %fiber above barrel cortex
files(37).type = 'ChAT';         %mouse ChR2(+/+). 
files(37).electrode_resist = []; %[MOhm]
files(37).depth = 229; %[um]
files(37).pr_whisker = [];
files(37).adj_whisker = [];                                            
files(37).headers = 2:5;
files(37).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(37).header_stim(2).type = 2;  
files(37).header_stim(3).type = 2;  
files(37).header_stim(4).type = 2;  
files(37).channel_Vm = 1;                        
files(37).channel_LFP = 12;                       
files(37).channel_galvano = 15;
files(37).channel_airpuff = 13;
files(37).channel_EKG = 6;
files(37).channel_EEG = 5;
files(37).channel_laser = 10;                %optogenetic stimulation
files(37).galvano = [];
files(37).comments = 'on amp=1 there is no light!, coupling between channels!';
files(37).offset = [];

files(38).name = 'Set2-2014-03-12-002.exp2';
files(38).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(38).exp = 'Barrel cortex LFP'; %fiber above barrel cortex
files(38).type = 'ChAT';         %mouse ChR2(+/+). 
files(38).electrode_resist = []; %[MOhm]
files(38).depth = 450; %[um]
files(38).pr_whisker = [];
files(38).adj_whisker = [];                                            
files(38).headers = 2:4;
files(38).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(38).header_stim(2).type = 2;  
files(38).header_stim(3).type = 2;  
files(38).channel_Vm = 1;                        
files(38).channel_LFP = 12;                       
files(38).channel_galvano = 15;
files(38).channel_airpuff = 13;
files(38).channel_EKG = 6;
files(38).channel_EEG = 5;
files(38).channel_laser = 10;                %optogenetic stimulation
files(38).galvano = [];
files(38).comments = 'on amp=1 there is no light!';
files(38).offset = [];

files(39).name = 'Set2-2014-03-12-003.exp2';
files(39).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(39).exp = 'Barrel cortex LFP'; %fiber above barrel cortex
files(39).type = 'ChAT';         %mouse ChR2(+/+). 
files(39).electrode_resist = []; %[MOhm]
files(39).depth = 700; %[um]
files(39).pr_whisker = [];
files(39).adj_whisker = [];                                            
files(39).headers = 2:4;
files(39).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(39).header_stim(2).type = 2;  
files(39).header_stim(3).type = 2;  
files(39).channel_Vm = 1;                        
files(39).channel_LFP = 12;                       
files(39).channel_galvano = 15;
files(39).channel_airpuff = 13;
files(39).channel_EKG = 6;
files(39).channel_EEG = 5;
files(39).channel_laser = 10;                %optogenetic stimulation
files(39).galvano = [];
files(39).comments = 'on amp=1 there is no light!';
files(39).offset = [];

files(40).name = 'Set2-2014-03-12-004.exp2';
files(40).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(40).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(40).type = 'ChAT';         %mouse ChR2(+/+).  Cell #2
files(40).electrode_resist = []; %[MOhm]
files(40).depth = 267; %[um]
files(40).pr_whisker = [];
files(40).adj_whisker = [];                                            
files(40).headers = 1:2;
files(40).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(40).header_stim(2).type = 7;  
files(40).channel_Vm = 1;                        
files(40).channel_LFP = 12;                       
files(40).channel_galvano = 15;
files(40).channel_airpuff = 13;
files(40).channel_EKG = 6;
files(40).channel_EEG = 5;
files(40).channel_laser = 10;                %optogenetic stimulation
files(40).galvano = [];
files(40).comments = '';
files(40).offset = [];

files(41).name = 'Set2-2014-03-12-005.exp2';
files(41).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(41).exp = 'Barrel cortex cell attached'; %fiber above barrel cortex
files(41).type = 'ChAT';         %mouse ChR2(+/+). Cell #3
files(41).electrode_resist = []; %[MOhm]
files(41).depth = 732; %[um]
files(41).pr_whisker = [];
files(41).adj_whisker = [];                                            
files(41).headers = 1:2;
files(41).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(41).header_stim(2).type = 7;  
files(41).channel_Vm = 1;                        
files(41).channel_LFP = 12;                       
files(41).channel_galvano = 15;
files(41).channel_airpuff = 13;
files(41).channel_EKG = 6;
files(41).channel_EEG = 5;
files(41).channel_laser = 10;                %optogenetic stimulation
files(41).galvano = [];
files(41).comments = '';
files(41).offset = [];

files(42).name = 'Set2-2014-03-12-006.exp2';
files(42).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(42).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(42).type = 'ChAT';         %mouse ChR2(+/+). Cell #4
files(42).electrode_resist = []; %[MOhm]
files(42).depth = 505; %[um]
files(42).pr_whisker = [];
files(42).adj_whisker = [];                                            
files(42).headers = 2;
files(42).header_stim(1).type = 7;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(42).channel_Vm = 1;                        
files(42).channel_LFP = 12;                       
files(42).channel_galvano = 15;
files(42).channel_airpuff = 13;
files(42).channel_EKG = 6;
files(42).channel_EEG = 5;
files(42).channel_laser = 10;                %optogenetic stimulation
files(42).galvano = [];
files(42).comments = '';
files(42).offset = [];

files(43).name = 'Set2-2014-03-12-007.exp2';
files(43).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(43).exp = 'Barrel cortex cell attached'; %fiber above barrel cortex
files(43).type = 'ChAT';         %mouse ChR2(+/+). Cell #5
files(43).electrode_resist = []; %[MOhm]
files(43).depth = 965; %[um]
files(43).pr_whisker = [];
files(43).adj_whisker = [];                                            
files(43).headers = 1:2;
files(43).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(43).header_stim(2).type = 7;  
files(43).channel_Vm = 1;                        
files(43).channel_LFP = 12;                       
files(43).channel_galvano = 15;
files(43).channel_airpuff = 13;
files(43).channel_EKG = 6;
files(43).channel_EEG = 5;
files(43).channel_laser = 10;                %optogenetic stimulation
files(43).galvano = [];
files(43).comments = '';
files(43).offset = 0;

files(44).name = 'Set2-2014-03-12-008.exp2';
files(44).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(44).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(44).type = 'ChAT';         %mouse ChR2(+/+). Cell #6
files(44).electrode_resist = []; %[MOhm]
files(44).depth = 558; %[um]
files(44).pr_whisker = [];
files(44).adj_whisker = [];                                            
files(44).headers = 2:3;
files(44).header_stim(1).type = 7;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(44).header_stim(2).type = 7;  
files(44).channel_Vm = 1;                        
files(44).channel_LFP = 12;                       
files(44).channel_galvano = 15;
files(44).channel_airpuff = 13;
files(44).channel_EKG = 6;
files(44).channel_EEG = 5;
files(44).channel_laser = 10;                %optogenetic stimulation
files(44).galvano = [];
files(44).comments = 'optic fiber was not directed at the right place';
files(44).offset = 0;

files(45).name = 'Set2-2014-03-17-001.exp2';
files(45).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(45).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(45).type = 'ChAT';         %mouse #96 ChR2(+/+). Cell #7
files(45).electrode_resist = 5; %[MOhm]
files(45).depth = 512; %[um]
files(45).pr_whisker = [];
files(45).adj_whisker = [];                                            
files(45).headers = 1;
files(45).header_stim(1).type = 7;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(45).channel_Vm = 1;                        
files(45).channel_LFP = 12;                       
files(45).channel_galvano = 15;
files(45).channel_airpuff = 13;
files(45).channel_EKG = 6;
files(45).channel_EEG = 5;
files(45).channel_laser = 10;                %optogenetic stimulation
files(45).galvano = [];
files(45).comments = 'high input resistance. cell was not opened properly';
files(45).offset = 6;

files(46).name = 'Set2-2014-03-17-002.exp2';
files(46).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(46).exp = 'Barrel cortex cell attached'; %fiber above barrel cortex
files(46).type = 'ChAT';         %mouse #96 ChR2(+/+). Cell #8
files(46).electrode_resist = []; %[MOhm]
files(46).depth = 513; %[um]
files(46).pr_whisker = [];
files(46).adj_whisker = [];                                            
files(46).headers = 1:3;
files(46).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(46).header_stim(2).type = 7;
files(46).header_stim(3).type = 1;
files(46).channel_Vm = 1;                        
files(46).channel_LFP = 12;                       
files(46).channel_galvano = 15;
files(46).channel_airpuff = 13;
files(46).channel_EKG = 6;
files(46).channel_EEG = 5;
files(46).channel_laser = 10;                %optogenetic stimulation
files(46).galvano = [];
files(46).comments = '';
files(46).offset = [];

files(47).name = 'Set2-2014-03-19-003.exp2';
files(47).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(47).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(47).type = 'ChAT';         %mouse #92 ChR2(+/+).  Cell #9
files(47).electrode_resist = []; %[MOhm]
files(47).depth = []; %[um]
files(47).pr_whisker = [];
files(47).adj_whisker = [];                                            
files(47).headers = 1;
files(47).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(47).channel_Vm = 1;                        
files(47).channel_LFP = 12;                       
files(47).channel_galvano = 15;
files(47).channel_airpuff = 13;
files(47).channel_EKG = 6;
files(47).channel_EEG = 5;
files(47).channel_laser = 10;                %optogenetic stimulation
files(47).galvano = 2;
files(47).comments = '';
files(47).offset = [];

files(48).name = 'Set2-2014-03-26-001.exp2';
files(48).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(48).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(48).type = 'ChAT';         %mouse #100 ChR2(+/+). Cell #10
files(48).electrode_resist = []; %[MOhm]
files(48).depth = 347; %[um]
files(48).pr_whisker = 'B1';
files(48).adj_whisker = [];                                            
files(48).headers = 1:2;
files(48).header_stim(1).type = 7;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(48).header_stim(2).type = 8;   
files(48).channel_Vm = 1;                        
files(48).channel_LFP = 12;                       
files(48).channel_galvano = 15;
files(48).channel_airpuff = 13;
files(48).channel_EKG = 6;
files(48).channel_EEG = 5;
files(48).channel_laser = 10;                %optogenetic stimulation
files(48).galvano = 2;
files(48).comments = '';
files(48).offset = 6;

files(49).name = 'Set2-2014-03-26-002.exp2';
files(49).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(49).exp = 'Barrel cortex LFP'; %fiber above barrel cortex
files(49).type = 'ChAT';         %mouse #100 ChR2(+/+). 
files(49).electrode_resist = []; %[MOhm]
files(49).depth = 347; %[um]
files(49).pr_whisker = 'B1';
files(49).adj_whisker = [];                                            
files(49).headers = 2;
files(49).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(49).channel_Vm = 1;                        
files(49).channel_LFP = 12;                       
files(49).channel_galvano = 15;
files(49).channel_airpuff = 13;
files(49).channel_EKG = 6;
files(49).channel_EEG = 5;
files(49).channel_laser = 10;                %optogenetic stimulation
files(49).galvano = 2;
files(49).comments = '';
files(49).offset = [];

files(50).name = 'Set2-2014-03-26-003.exp2';
files(50).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(50).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(50).type = 'ChAT';         %mouse #100 ChR2(+/+). Cell #11
files(50).electrode_resist = []; %[MOhm]
files(50).depth = 460; %[um]
files(50).pr_whisker = 'B1';
files(50).adj_whisker = [];                                            
files(50).headers = 2:4;
files(50).header_stim(1).type = 8;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(50).header_stim(2).type = 1;  
files(50).header_stim(3).type = 2;   
files(50).channel_Vm = 1;                        
files(50).channel_LFP = 12;                       
files(50).channel_galvano = 15;
files(50).channel_airpuff = 13;
files(50).channel_EKG = 6;
files(50).channel_EEG = 5;
files(50).channel_laser = 10;                %optogenetic stimulation
files(50).galvano = 2;
files(50).comments = 'high input resistance';
files(50).offset = -17;

files(51).name = 'Set2-2014-03-26-004.exp2';
files(51).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(51).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(51).type = 'ChAT';         %mouse #100 ChR2(+/+). Cell #12
files(51).electrode_resist = []; %[MOhm]
files(51).depth = 259; %[um]
files(51).pr_whisker = 'D2';
files(51).adj_whisker = [];                                            
files(51).headers = 2:5;
files(51).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(51).header_stim(2).type = 2;  
files(51).header_stim(3).type = 5;  
files(51).header_stim(4).type = 8;   
files(51).channel_Vm = 1;                        
files(51).channel_LFP = 12;                       
files(51).channel_galvano = 15;
files(51).channel_airpuff = 13;
files(51).channel_EKG = 6;
files(51).channel_EEG = 5;
files(51).channel_laser = 10;                %optogenetic stimulation
files(51).galvano = 2;
files(51).comments = '';
files(51).offset = [];

files(52).name = 'Set2-2014-04-02-001.exp2';
files(52).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(52).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(52).type = 'ChAT';         %mouse #113 ChR2(+/+). Cell #13
files(52).electrode_resist = []; %[MOhm]
files(52).depth = 305; %[um]
files(52).pr_whisker = 'B1';
files(52).adj_whisker = [];                                            
files(52).headers = 2:4;
files(52).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(52).header_stim(2).type = 2;  
files(52).header_stim(3).type = 5;  
files(52).channel_Vm = 1;                        
files(52).channel_LFP = 12;                       
files(52).channel_galvano = 15;
files(52).channel_airpuff = 13;
files(52).channel_EKG = 6;
files(52).channel_EEG = 5;
files(52).channel_laser = 10;                %optogenetic stimulation
files(52).galvano = 2;
files(52).comments = '';
files(52).offset = [];

files(53).name = 'Set2-2014-04-02-002.exp2';
files(53).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(53).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(53).type = 'ChAT';         %mouse #113 ChR2(+/+). Cell #14
files(53).electrode_resist = []; %[MOhm]
files(53).depth = []; %[um]
files(53).pr_whisker = 'B1';
files(53).adj_whisker = [];                                            
files(53).headers = 2:3;
files(53).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(53).header_stim(2).type = 8;  
files(53).channel_Vm = 1;                        
files(53).channel_LFP = 12;                       
files(53).channel_galvano = 15;
files(53).channel_airpuff = 13;
files(53).channel_EKG = 6;
files(53).channel_EEG = 5;
files(53).channel_laser = 10;                %optogenetic stimulation
files(53).galvano = 2;
files(53).comments = '';
files(53).offset = [];

files(54).name = 'Set2-2014-04-03-001.exp2';
files(54).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(54).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(54).type = 'ChAT';         %mouse #95 ChR2(+/+). Cell #15
files(54).electrode_resist = []; %[MOhm]
files(54).depth = 350; %[um]
files(54).pr_whisker = 'D1';
files(54).adj_whisker = [];                                            
files(54).headers = 2:4;
files(54).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(54).header_stim(2).type = 1;  
files(54).header_stim(3).type = 2;  
files(54).channel_Vm = 1;                        
files(54).channel_LFP = 12;                       
files(54).channel_galvano = 15;
files(54).channel_airpuff = 13;
files(54).channel_EKG = 6;
files(54).channel_EEG = 5;
files(54).channel_laser = 10;                %optogenetic stimulation
files(54).galvano = 2;
files(54).comments = '';
files(54).offset = 10;

files(55).name = 'Set2-2014-04-03-002.exp2';
files(55).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(55).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(55).type = 'ChAT';         %mouse #95 ChR2(+/+). Cell #16
files(55).electrode_resist = []; %[MOhm]
files(55).depth = 406; %[um]
files(55).pr_whisker = 'D1';
files(55).adj_whisker = [];                                            
files(55).headers = 2:3;
files(55).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(55).header_stim(2).type = 2;  
files(55).channel_Vm = 1;                        
files(55).channel_LFP = 12;                       
files(55).channel_galvano = 15;
files(55).channel_airpuff = 13;
files(55).channel_EKG = 6;
files(55).channel_EEG = 5;
files(55).channel_laser = 10;                %optogenetic stimulation
files(55).galvano = 2;
files(55).comments = [];
files(55).offset = 15;

files(56).name = 'Set2-2014-04-03-003.exp2';
files(56).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(56).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(56).type = 'ChAT';         %mouse #95 ChR2(+/+). Cell #17
files(56).electrode_resist = []; %[MOhm]
files(56).depth = 464; %[um]
files(56).pr_whisker = 'D1';
files(56).adj_whisker = [];                                            
files(56).headers = 2:8;
files(56).header_stim(1).type = 1;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(56).header_stim(2).type = 2;  
files(56).header_stim(3).type = 2;  
files(56).header_stim(4).type = 1;  
files(56).header_stim(5).type = 5;  
files(56).header_stim(6).type = 5;  
files(56).header_stim(7).type = 8;  
files(56).channel_Vm = 1;                        
files(56).channel_LFP = 12;                       
files(56).channel_galvano = 15;
files(56).channel_airpuff = 13;
files(56).channel_EKG = 6;
files(56).channel_EEG = 5;
files(56).channel_laser = 10;                %optogenetic stimulation
files(56).galvano = 2;
files(56).comments = [];
files(56).offset = 36;

files(57).name = 'Set2-2014-04-03-004.exp2';
files(57).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(57).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(57).type = 'ChAT';         %mouse #95 ChR2(+/+). Cell #18
files(57).electrode_resist = []; %[MOhm]
files(57).depth = 439; %[um]
files(57).pr_whisker = 'D1';
files(57).adj_whisker = [];                                            
files(57).headers = 2:5;
files(57).header_stim(1).type = 5;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(57).header_stim(2).type = 1;  
files(57).header_stim(3).type = 8;  
files(57).header_stim(4).type = 8;  
files(57).channel_Vm = 1;                        
files(57).channel_LFP = 12;                       
files(57).channel_galvano = 15;
files(57).channel_airpuff = 13;
files(57).channel_EKG = 6;
files(57).channel_EEG = 5;
files(57).channel_laser = 10;                %optogenetic stimulation
files(57).galvano = 2;
files(57).comments = 'high input resistance';
files(57).offset = 15;

files(58).name = 'Set2-2014-04-03-005.exp2';
files(58).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(58).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(58).type = 'ChAT';         %mouse #95 ChR2(+/+). Cell #19
files(58).electrode_resist = []; %[MOhm]
files(58).depth = 587; %[um]
files(58).pr_whisker = 'D1';
files(58).adj_whisker = [];                                            
files(58).headers = 2:3;
files(58).header_stim(1).type = 5;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(58).header_stim(2).type = 2;  
files(58).channel_Vm = 1;                        
files(58).channel_LFP = 12;                       
files(58).channel_galvano = 15;
files(58).channel_airpuff = 13;
files(58).channel_EKG = 6;
files(58).channel_EEG = 5;
files(58).channel_laser = 10;                %optogenetic stimulation
files(58).galvano = 2;
files(58).comments = '';
files(58).offset = 4;

files(59).name = 'Set2-2014-04-03-006.exp2';
files(59).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(59).exp = 'Barrel cortex intracellular'; %fiber above barrel cortex
files(59).type = 'ChAT';         %mouse #95 ChR2(+/+). Cell #20
files(59).electrode_resist = []; %[MOhm]
files(59).depth = 406; %[um]
files(59).pr_whisker = [];
files(59).adj_whisker = [];                                            
files(59).headers = 2:11;
files(59).header_stim(1).type = 2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(59).header_stim(2).type = 8;  
files(59).header_stim(3).type = 8;  
files(59).header_stim(4).type = 8;  
files(59).header_stim(5).type = 3;  
files(59).header_stim(6).type = 4;  
files(59).header_stim(7).type = 2;  
files(59).header_stim(8).type = 1;  
files(59).header_stim(9).type = 1;  
files(59).header_stim(10).type = 2;  
files(59).channel_Vm = 1;                        
files(59).channel_LFP = 12;                       
files(59).channel_galvano = 15;
files(59).channel_airpuff = 13;
files(59).channel_EKG = 6;
files(59).channel_EEG = 5;
files(59).channel_laser = 10;                %optogenetic stimulation
files(59).galvano = 2;
files(59).comments = 'high input resistance. galvo on the wrong whisker';
files(59).offset = 9;

files(60).name = 'Set2-2014-04-03-007.exp2';
files(60).path = 'D:\Inbal M.Sc\Data PhD\ChAT Data\Raw Data';
files(60).exp = 'Barrel cortex LFP'; %fiber above barrel cortex
files(60).type = 'ChAT';         %mouse #95 ChR2(+/+). 
files(60).electrode_resist = []; %[MOhm]
files(60).depth = 461; %[um]
files(60).pr_whisker = [];
files(60).adj_whisker = [];                                            
files(60).headers = 2;
files(60).header_stim(1).type =2;                        % 1=spont alone, 2=spont+laser, 3=puff alone, 4=puff+laser, 5=galvano alone, 6=galvano+laser, 7=protocol airpuff, 8=protocol galvano         
files(60).channel_Vm = 1;                        
files(60).channel_LFP = 12;                       
files(60).channel_galvano = 15;
files(60).channel_airpuff = 13;
files(60).channel_EKG = 6;
files(60).channel_EEG = 5;
files(60).channel_laser = 10;                %optogenetic stimulation
files(60).galvano = 2;
files(60).comments = '';
files(60).offset = [];
